### ISSUE TITLE
Massive desync issues

### ISSUE THREAD

**Issue by Ze-Rax** [Ze-Rax/TrackmaniaFlagRush#104]
The players can go completely out of sync leading to the players being displayed on completely different locations then they actually are at.

This is most likely due to us having switched to fine Extrapolation. In that case we might have to go back to crude extrapolation.

Right now we got server 1-3 running back on crude Extrapolation to check if that actually fixes the issue.

If so, then Todo:
- In `InitPlayer()`: `Player.UseCrudeExtrapolation = S_UseCrudExtrapolation;`
This setting is already available from the modebase, default False and hidden.

**Comment by reaby** [comment]
note to disable minimap:  minimap won't work since playerpositions are not updated at clientside.
