### ISSUE TITLE
fix spec/disconnect icons at scoreboard + add join team buttons

### ISSUE THREAD

**Issue by reaby** [Ze-Rax/TrackmaniaFlagRush#117]
![kuva](https://user-images.githubusercontent.com/1789509/147288052-75f197b7-04c1-408f-b347-b74ffca243a3.png)

- [x] Move icons
- [ ] Add Button join team 1
- [ ] Add Button join team 2

**Comment by Ze-Rax** [comment]
oops

**Comment by Ze-Rax** [comment]
Icons moved in 6e2b51c
