### ISSUE TITLE
Automatic warmup countdown setting

### ISSUE THREAD

**Issue by Geekid812** [Ze-Rax/TrackmaniaFlagRush#196]
A setting to automatically end the warmup after a specific amount of time (countdown starts with warmup but can be sped up if all players are ready).
Could be useful for automatic games or for use in tournaments when the timing of each match must be precise.

**Comment by Ze-Rax** [comment]
I honestly don't wanna bloat the warmup with even more timers. As of right now:
- Infinite warmup
- If at least 1 player in each team is ready -> 60s countdown.
- If all players are ready -> 5s countdown.

If timing in tournament settings or whatever are so important, then there's always a way to have an admin skip warmup using ModeCommands UI or Servercontrollers.
