### ISSUE TITLE
Add Time Remaining warning

### ISSUE THREAD

**Issue by Geekid812** [Ze-Rax/TrackmaniaFlagRush#69]
From my observations it can happen that people are not aware of the timer even though it is displayed on the score header itself. I think implementing a time warning such as "30 seconds remaining" and making the timer red/blinking could solve this.

No ideas on the implementation yet. That's to be discussed in the dev channel.

**Comment by Ze-Rax** [comment]
Ideas can also be posted here, doesn'T need to be discussed exclusively in the dev channel. Writing down ideas and information here might also help to keep track of it.
