### ISSUE TITLE
Improved hitboxes

### ISSUE THREAD

**Issue by Ze-Rax** [Ze-Rax/TrackmaniaFlagRush#71]
We somehow need to implement box shaped hitboxes that rotate with the car... Does someone know how the math for that works?

(Axisaligned Bounding boxes (AABB) won't suffice)

**Comment by Geekid812** [comment]
I thought that's already how it worked. If that's not the case, then I don't know who's willing to go dig in the lib...

**Comment by Ze-Rax** [comment]
The current implementation are cylinders which are always axisaligned to the vertical axis

**Comment by Ze-Rax** [comment]
For OBB we would need the forward, right & up vectors of the car. These would be available in `Player.Vehicle`, but the Gamemode doesn't have information about the Vehilces of the Players. In fact, a client only has information about his own vehicle. Vehicles of other players are Null (Checked with Openplanet).

The only orientation information we got `Player.AimDirection` (`Vec3`), `Player.AimPitch` (`Real`) and `Player.AimYaw` (`Real`), which - as far as I can tell - won't be enough to compute the up and right vectors.

**Comment by Ze-Rax** [comment]
`Player.UseCrudeInterpolation` makes `Player.Vehicle` available, which contains direction, up and left vectors.

**Comment by reaby** [comment]
Implemented at e92082481bc3b4d23d4859f3357c4afc71396954
